### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by ghost** [franckverrot/arnoldc.rb#1]
I am having problems with installing ArnoldC to my Ruby directory.

It keeps saying:
"ERROR:  Could not find a valid gem 'arnoldc' (>= 0) in any repository"

I am in need of assistance.

**Comment by franckverrot** [comment]
I got that Ruby gem name wrong... and you might be the first to really care 😆 

Here's the [commit that fixes it](https://github.com/franckverrot/arnoldc.rb/commit/865098ab88043ee1fb590d35bb29de0b6663e290), so you just need to `gem install` it and things should work.

Cheers!
